include:
  - proxy.yaml

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    networks:
      backend:
        ipv4_address: 172.20.0.5
    environment:
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_TABLE=requests
      - DB_HOST=db
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - 3306:3306
    networks:
      backend:
        ipv4_address: 172.20.0.10
    env_file: ".env"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 6s
      retries: 10